baseURL = 'https://pinapinv.github.io/portafolioPP/'
languageCode = 'es-mx'
title = ' Fernanda Flores'
theme = 'stack'

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]
  description = "Portafolio de prÃ¡cticas de Paradigmas de ProgramaciÃ³n"
  
  [params.author]
    name = "Fernanda Valenzuela"
    email = "f376160@uabc.edu.mx"
  
  [params.footer]
    since = 2025
    customText = "Estudiante de IngenierÃ­a en Software"
  
  [params.sidebar]
  emoji = "ğŸ‘©â€ğŸ’»"
  subtitle = "Portafolio de PrÃ¡cticas de Paradigmas"


  
  [params.article]
    math = false
    toc = true
    readingTime = true
    
    [params.article.license]
      enabled = false
  
  [params.comments]
    enabled = false
  
  [params.widgets]
    homepage = ["search", "archives", "tag-cloud"]
    page = ["toc"]
  
  [params.widgets.archives]
    limit = 5
  
  [params.widgets.tagCloud]
    limit = 20

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Inicio"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "categories"
    name = "ğŸ“‚ CategorÃ­as"
    url = "/categories/"
    weight = 3
    
  [[menu.main]]
    identifier = "tags"
    name = "ğŸ·ï¸ Tags"
    url = "/tags/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
  [markup.highlight]
    noClasses = false
    lineNos = true

[taxonomies]
  category = "categories"
  tag = "tags"